- template:
    src: bird.j2
    dest: /etc/bird.conf
    owner: root

- name: test bird
  shell: docker ps -q bird
  register: if_bird_exist
  ignore_errors: true

- name: install bird
  shell: docker run -d --restart=on-failure
    -v /etc/bird.conf:/etc/bird.conf
    --net=host --cap-add=NET_ADMIN
    --name=bird
    imlonghao/bird
  when: if_bird_exist.rc == 1

- name: reload config
  shell: docker exec bird /birdc conf
  when: if_bird_exist.rc == 0
