- template:
    src: bird.j2
    dest: /etc/bird.conf
    owner: root

- name: test bird
  shell: docker inspect bird
  register: if_bird_exist
  ignore_errors: true

- name: install bird
  shell: docker run -d --restart=on-failure
    -v /etc/bird.conf:/etc/bird.conf
    --net=host --cap-add=NET_ADMIN
    --name=bird
    imlonghao/bird
  when: '"No such object" in if_bird_exist.stdout'

- name: reload config
  shell: docker exec bird /birdc conf
  when: (if_bird_exist.stdout|from_json)[0]["State"]["Running"]

- name: start bird
  shell: docker start bird
  when: (if_bird_exist.stdout|from_json)[0]["State"]["Running"] == False
